### ISSUE TITLE
Slide slider doesn't match parameter

### ISSUE THREAD

**Issue by matthewpaul-us** [timothyqiu/gdfxr#1]
I've been playing around with the Slide functionality. It appears that the slide slider only allows an ascending slide, rather than both an ascending and descending slide. This limitation isn't a part of the core implementation because if you random generate something like a laser then the sound will have a descending slide. The slider will be set to its lowest point. Changing the slider at all will result in the descending slide being turned into either a neutral sound or an ascending sound.

Steps to reproduce:
1. Install plugin
2. Generate a sound that uses a descending slide such as Laser/Shoot
3. Play the sound and confirm a descending sound
4. Change the Slide slider at all
5. Play the sound to hear either a sound with no slide (Slider all the way to the left) or with some amount of ascending slide (Slider anywhere else

**Comment by timothyqiu** [comment]
Thanks for pointing this out. I forgot to set the slider min value for these kind of parameters to -1.

**Comment by matthewpaul-us** [comment]
WOW! A fix within an hour and a better one than the hack I put together. Many thanks!
