### ISSUE TITLE
Request: Port to Godot 4.

### ISSUE THREAD

**Issue by harrisyu** [timothyqiu/gdfxr#3]
你好~感谢你制作的插件，现阶段是不是可以考虑移植到 Godot 4 了？ 现在 Godot 4 进入 Beta 阶段，API 已经基本稳定了。

**Comment by timothyqiu** [comment]
我准备这周末试一试 :)

**Comment by timothyqiu** [comment]
gdfxr now works on Godot 4 :tada: 

See the [godot-4](https://github.com/timothyqiu/gdfxr/tree/godot-4) branch. When porting, I found that there're still a few places that might be a Godot bug. My current workaround seems hacky. So I'd like to wait for a few more betas to release this :)

可以看上面的 [godot-4](https://github.com/timothyqiu/gdfxr/tree/godot-4) 分支。移植的过程中我发现还有一些可能是 Godot 的 bug 的地方，我目前的解决方法只是临时方案。所以我准备等等再发布 :)

**Comment by harrisyu** [comment]
感谢~辛苦了~
试了一下没什么问题，有一些报错，不懂是不是你说的 bug
似乎就是 import_plugin.gd 少个 _get_priority 的函数
```
func _get_priority():
	return 1.0


 func _import(source_file, save_path, options, platform_variants, gen_files):
```

**Comment by timothyqiu** [comment]
我这里没有报 `_get_priority()` 的错，理论上这个方法是有默认实现的，所以可以不加。

我觉得有问题的主要是主题的通知顺序之类的，按照 3.x 的写在初始化的时候会拿不到图标，所以我加了一些临时的代码去重复获取。
