### ISSUE TITLE
hope can output wav format

### ISSUE THREAD

**Issue by WuMing757** [timothyqiu/gdfxr#4]
can not load like this  = load("res://assets/music/effect/xx.sfxr"). hope the sound can be output as wav format.

**Comment by timothyqiu** [comment]
`load("res://assets/music/effect/xx.sfxr")` is exactly how you use the sfxr file in code. It will be loaded as an `AudioStreamSample`, and thus you can save it to wav with `save_to_wav()`.

**Comment by WuMing757** [comment]
great!
