### ISSUE TITLE
Quick Duplicate option?

### ISSUE THREAD

**Issue by russmatney** [timothyqiu/gdfxr#7]
Hey there! Thanks for gdfxr, it's an excellent godot addon :)

In my own repo, I added a convenient option for quickly saving a file with a similar name - it's one click to save-as 'jump2', another to save-as 'jump3', etc. For my usage I want to quickly create a handful of similar sounds for any effect. This makes it super quick to get a few sounds made (click mutate, click save-dupe, click mutate, click save-dupe, etc).

Are you open to a feature like this? I'm happy to clean this up a bit and open a proper pull request - or if you feel strongly and have the bandwidth, feel free to work from what I've done here:

godot 4: https://github.com/russmatney/dino/commit/9c9f08cf38e4e77c3eb3618cfde7caec69d65b6b

godot 3: https://github.com/russmatney/dino/commit/f28459fe436f5b10ada14558c92b9e5d4497f7d4

Note that the incrementing number on the filename is only set to work for single digit filenames right now - it could be handled better, this was just a quick and dirty version.

Let me know what you think!

**Comment by timothyqiu** [comment]
Hi, I made some adjustments based on your work :)

Since the "Save As" option lacks a default filename, I merged your "Duplicate" option into the "Save As" option. Multiple digit filenames should also be handled correctly now.

You can try the lastest `master` or `godot-4` branch.

**Comment by russmatney** [comment]
Excellent! Thanks for the quick work - I’ll grab the latest and try it out soon.

**Comment by russmatney** [comment]
The latest works great (tho I only tested the godot-4 branch). I like your implementation better - people will probably stumble upon this nice workflow. Also, I appreciate the co-author credit, thanks much!
